name: flutter_crud_test
description: "A simple CRUD app with flutter"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  # --- state management ---
  get: ^4.6.6

  # --- http client ---
  milky_http_client:
    path: packages/milky_http_client

  # --- others ---
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#flutter:

